### ISSUE TITLE
Finish the router re-write complete with tests.

### ISSUE THREAD

**Issue by skeswa** [skeswa/gophr#161]
The router was the first part of gophr that was ever built. It has started to show its age. It is time to bring it up to code with the rest of the codebase while correcting some issues that `go get` was having with gophr.pm urls.

**Comment by Shikkic** [comment]
Question. Now that we've faced our first real issues with router + sub versioner in prod I think it might be time to address how to reproduce `go get` properly in dev. Currently we don't properly sub-version all packages in a repo. Meaning it starts at the root package you version and then stops. In other words it doesn't mimic the recursive nature of a go get which is the functionality I think might be breaking in prod.

Would fixing the problem with the import statements in fix theses issues in dev?

**Comment by skeswa** [comment]
I think the design now is fine, and will work with go-get in dev as soon as I correct the router. What is:

> the problem with import statements

**Comment by Shikkic** [comment]
Awesome thats really good news then. The issues are one in the same I mean't ` no go-import meta tags` issues
