### ISSUE TITLE
[Sub-versioner] - Bug in prod

### ISSUE THREAD

**Issue by Shikkic** [skeswa/gophr#162]
Received this bug in prod

```
2016/09/14 05:22:31 Could not repsond to request with non-public error: Error, could not rename archive folder to target folder. rename /construction-zone/go.uuid-v1.1.0 /construction-zone/6satori7go.uuid: no such file or directory
```

**Comment by Shikkic** [comment]
I find it very odd that when I run a request that breaks prod, it doesn't break dev. The outputs aren't even the same? 

Here was the request `go get -v gophr.pm/skeswa/gophr@0.2.7`

**Comment by Shikkic** [comment]
Here is prod output
![screen shot 2016-09-14 at 3 05 54 am](https://cloud.githubusercontent.com/assets/8765687/18502976/77964b44-7a28-11e6-96c0-04d29000bf44.png)

**Comment by Shikkic** [comment]
Here is dev output
![screen shot 2016-09-14 at 3 05 35 am](https://cloud.githubusercontent.com/assets/8765687/18502983/82f98f28-7a28-11e6-8865-02f2a7accb19.png)

**Comment by Shikkic** [comment]
Notice that the `archive` and `target` folders have different names. Dev uses refs which is correct and known issue that we fixed in the past, specially to fix this problem. The other users version tags.

**Comment by Shikkic** [comment]
Idk how this could be possible but my first inclination is that these two samples are using different versions of the code base. The prod output seems to be using an outdated copy of the `sub-versioner`. If you look at the `dev` output towards the bottom after `/target`. There is only once instance of the line `/construction-zone/....` in dev and two in prod (both of which are incorrect in prod).

**Comment by Shikkic** [comment]
The short of it is. This bug is not currently possible with our current setup. We changed our router code and our sub-versioner code long ago, so that we never have an instance where we're not passing refs in the sub-versioner.

Maybe we need to rebuild the router images and recycle them?

**Comment by skeswa** [comment]
I still think that we should write tests to ensure that we catch something like this at the PR stage - even if it is just a deployment mistake.

**Comment by Shikkic** [comment]
Absolutely, I'm totally with you on that. 

Also, I just tested this again and now it seems to have resolved it self and is working again. The tests that broke before now.

**Comment by Shikkic** [comment]
In response to the testing. I definitely want to make it more of a personal responsibility to test more as well.
