### ISSUE TITLE
Create Cassandra + Lucene Index Docker Container

### ISSUE THREAD

**Issue by Shikkic** [skeswa/gophr#18]
We'll need to create a docker container for elastisearch and get the config scripts setup

**Comment by skeswa** [comment]
I'll take care if this one, because I'm more familiar with the infra.

**Comment by Shikkic** [comment]
I was hoping to get a chance to go through the process of creating a container and writing the config for it, if thats cool. Or if we could pair for part of it that'd be super helpful

**Comment by skeswa** [comment]
Pairing it is a great idea.
